#pragma once

// from glfw3.h
#define BU_MOUSE_BUTTON_1      0
#define BU_MOUSE_BUTTON_2      1
#define BU_MOUSE_BUTTON_3      2
#define BU_MOUSE_BUTTON_4      3
#define BU_MOUSE_BUTTON_5      4
#define BU_MOUSE_BUTTON_6      5
#define BU_MOUSE_BUTTON_7      6
#define BU_MOUSE_BUTTON_8      7
#define BU_MOUSE_BUTTON_LAST   BU_MOUSE_BUTTON_8
#define BU_MOUSE_BUTTON_LEFT   BU_MOUSE_BUTTON_1
#define BU_MOUSE_BUTTON_RIGHT  BU_MOUSE_BUTTON_2
#define BU_MOUSE_BUTTON_MIDDLE BU_MOUSE_BUTTON_3